// POST Action
export const POST_FILE_REQUEST = "POST_FILE_REQUEST"
export const POST_FILE_SUCCESS = "POST_FILE_SUCCESS"
export const POST_FILE_FAILURE = "POST_FILE_FAILURE"

// GET Action
export const GET_SERVER_REQUEST = "GET_SERVER_REQUEST"
export const GET_SERVER_SUCCESS = "GET_SERVER_SUCCESS"
export const GET_SERVER_FAILURE = "GET_SERVER_FAILURE"

export const GET_FILE_REQUEST = "GET_FILE_REQUEST"
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS"
export const GET_FILE_FAILURE = "GET_FILE_FAILURE"

export const GET_FILE_LIST_REQUEST = "GET_FILE_LIST_REQUEST"
export const GET_FILE_LIST_SUCCESS = "GET_FILE_LIST_SUCCESS"
export const GET_FILE_LIST_FAILURE = "GET_FILE_LIST_FAILURE"

// Delete Action
export const DELETE_FILE_REQUEST = "DELETE_FILE_REQUEST"
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS"
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE"

// Progress Action
export const GET_PROGRESS = "GET_PROGRESS"